plugins {
    id 'java-library'
    // https://plugins.gradle.org/plugin/edu.sc.seis.launch4j
    id 'edu.sc.seis.launch4j' version '4.0.0'
}

dependencies {
    def mapsforgeVersion = "master-SNAPSHOT"
    // def mapsforgeVersion = "0.28.0"

    implementation "com.github.mapsforge.mapsforge:mapsforge-core:${mapsforgeVersion}"
    implementation "com.github.mapsforge.mapsforge:mapsforge-map:${mapsforgeVersion}"
    implementation "com.github.mapsforge.mapsforge:mapsforge-map-awt:${mapsforgeVersion}"
    implementation "com.github.mapsforge.mapsforge:mapsforge-map-reader:${mapsforgeVersion}"
    implementation "com.github.mapsforge.mapsforge:mapsforge-themes:${mapsforgeVersion}"
    api 'org.beanshell:bsh:+'
    api 'commons-codec:commons-codec:+'
    api 'commons-io:commons-io:+'
    api 'org.apache.commons:commons-lang3:+'
    api 'org.apache.commons:commons-text:+'
    api 'com.github.kerner1000:javapng:+'
    api 'org.xerial:sqlite-jdbc:+'
    api 'com.sleepycat:je:+'
    api 'org.glassfish.jaxb:jaxb-runtime:+'
    api 'org.slf4j:slf4j-api:+'
    implementation 'org.apache.httpcomponents.client5:httpclient5:+'
    implementation 'com.twelvemonkeys.imageio:imageio-webp:+'
    implementation 'ch.qos.logback:logback-classic:+'
    implementation 'org.slf4j:jul-to-slf4j:+'
    implementation 'net.sf.jtidy:jtidy:+'
    implementation 'com.itextpdf:itextpdf:+'
    implementation 'javax.media:jai-core:+'
    implementation 'com.sun.media:jai-codec:+'
    testImplementation 'org.jboss.resteasy:tjws:2.3.10.Final'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testImplementation 'javax.servlet:servlet-api:2.5'

    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
}
processResources {
    doLast {
        def targetDir = new File(sourceSets.main.output.resourcesDir, "mobac")
        targetDir.mkdirs()
        def props = new Properties()
        props.setProperty("mobac.gitBranchName", rootProject.gitBranchName)
        props.setProperty("mobac.gitCommitHash", rootProject.gitCommitHash)
        props.setProperty("mobac.gitCommitTime", rootProject.gitCommitTime)
        props.setProperty("mobac.version", "$projectVersion")
        new File(targetDir, "mobac-rev.properties").withWriter { props.store(it, null) }
    }
}
jar {
    // println("GIT branch $gitBranchName commit $gitCommitHash")

    manifest {
        attributes 'Main-Class': 'mobac.StartMOBAC'
        attributes 'Version': project.rootProject.version
        attributes "GitBranch": providers.gradleProperty("gitBranchName")
        attributes "GitCommitHash": providers.gradleProperty("gitCommitHash")
        attributes "GitCommitTime": providers.gradleProperty("gitCommitTime")
        attributes 'Build-Timestamp': new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ").format(new Date())

        // This entry is required by jaxb-runtime to work properly on Java 16+ - otherwise you will encounter
        // java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because
        // "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
        attributes 'Multi-Release': 'true'

        attributes 'Add-Exports': 'java.base/sun.net.www.protocol.http java.base/sun.net.www.protocol.https'
    }
    getArchiveBaseName().set('Mobile_Atlas_Creator')
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    exclude("module-info.class")
    exclude("META-INF/*.txt")
    exclude("META-INF/*.md")
    exclude("META-INF/MANIFEST.MF")
    exclude("META-INF/maven/*")
    // We only support 64 bit common architectures and platforms, remove the rest
    exclude("org/sqlite/native/Windows/x86/**")
    exclude("org/sqlite/native/Windows/armv7/**")
    exclude("org/sqlite/native/Linux/arm*/**")
    exclude("org/sqlite/native/Linux/x86/**")
    exclude("org/sqlite/native/Linux/ppc64/**")
    exclude("org/sqlite/native/Linux-Musl/**")
    exclude("org/sqlite/native/Linux-Android/**")
    exclude("org/sqlite/native/FreeBSD/**")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

launch4j {
    productName = "Mobile Atlas Creator"
    fileDescription = "Mobile Atlas Creator Windows Launcher"
    // only take the number+dot part at the beginning
    version = project.rootProject.version.toString().replaceAll('^([0-9\\.]+).*', '$1')
    textVersion = project.rootProject.version
    copyright = "MOBAC developers"
    companyName = ""
    icon = "${projectDir}/launch4j/mobac.ico"
    downloadUrl = "https://mobac.sourceforge.io/OpenJDK/"
    jreMinVersion = '1.11.0'
    requires64Bit = true
    dontWrapJar = true
    libraryDir = ""
    copyConfigurable = [] //["${project.buildDir}/libs/Mobile_Atlas_Creator.jar"]
    outfile = "Mobile Atlas Creator.exe"
}

test {
    useJUnitPlatform()
}